// <auto-generated />
namespace OEEPortal_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class start_end_machineoutputrecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start_end_machineoutputrecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201508200508388_start_end_machineoutputrecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
